FROM docker.io/golang:1.11

ADD https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

WORKDIR $GOPATH/src/github.com/openlab-red/mutating-webhook-vault-agent

COPY Gopkg.toml Gopkg.lock ./

RUN dep ensure --vendor-only
