apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: vault-agent-webhook-psp
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-agent-webhook-clusterrole
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - vault-agent-webhook-psp
  verbs:
  - use
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups: [""]
  resources:
  - configmap
  verbs:
  - get
  - list
  - watch
  - patch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-agent-webhook

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vault-agent-webhook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-agent-webhook-clusterrole
subjects:
- kind: ServiceAccount
  name: vault-agent-webhook
  namespace: hashicorp-vault
